### ISSUE TITLE
raspberry pi gpu

### ISSUE THREAD

**Issue by Grabber** [thomaspark-pkj/darknet-nnpack#6]
https://github.com/nineties/py-videocore

**Comment by thomaspark-pkj** [comment]
@Grabber Do you know how can get mAP of YOLO? I can get recall but I cannot find how to get mAP.

**Comment by shizukachan** [comment]
I have implemented idein's qmkl (at https://github.com/Idein/qmkl) to accelerate the GEMM in convolutional_layer.c / gemm.c. 

On a Pi Zero this may pay off, but I wasn't able to beat NNPACK-darknet's performance on the Raspberry Pi 3. Interestingly, copying the matrix buffers to/from GPU/system memory is faster than allocating them in GPU memory space. I presume this is probably because of MTRRs (or the ARM equivalent) leading to poor cache performance.
